[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  [headers."/*"]
    [headers."/*".values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Content-Security-Policy = "default-src 'self'"